# Generated by Django 6.0.2 on 2026-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.IntegerField(max_length=15)),
                ("age", models.IntegerField(max_length=4)),
                ("city", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=500)),
            ],
        ),
    ]
