# Generated by Django 6.0.2 on 2026-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universityapps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
